spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://172.17.0.2:3306/javatechie
    password: root
  batch:
    job:
    #disabled job run at startup
      enabled: 'false'
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '9191'
